In [1]:
# import numpy as np
# list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
# array_list = np.array(object = list_)

In [2]:
# Q1. Is there any difference in the data type of variables list_ and array_list? 
# If there is then write a code to print the data types of both the variables.

In [3]:
import numpy as np

In [20]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

In [21]:
# Ans -1. There is a difference between both the variable.
#2. list_ is a list of objects created in a python 
# 3. array_list is a varible which is a n-diemnesional array which has all elemnets of list_ variable.
# following way we can get the data type of both the variables

In [14]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [22]:
array_list.dtype # it is a n-dimensional array

dtype('<U1')

In [23]:
type(list_) # data type is list

list

In [19]:
type(array_list)

numpy.ndarray

In [24]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [35]:
for i in list_:
    print(type(i))    

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [37]:
for i in np.nditer(array_list):
    print(i.dtype)

<U1
<U1
<U1
<U1
<U1


In [38]:
for i in np.nditer(array_list):
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [43]:
# Q3. Considering the following changes in the variable, array_list:

In [39]:
array_list = np.array(object = list_, dtype = int)

In [44]:
# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? 
# If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [45]:
# Ans - by adding dtype = int in the above code, we are forcefully converting the datatype of all elements in array_list to integers.

In [46]:
# code for checking the data type post the changes

In [42]:
for i in np.nditer(array_list):
    print(i.dtype)

int64
int64
int64
int64
int64


In [41]:
array_list.dtype 

dtype('int64')

In [47]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [48]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [49]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
num_array.shape

(2, 3)

In [51]:
# two rows and 3 columns

In [52]:
num_array.size

6

In [53]:
# gives the total no. of elements in the array

In [54]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [55]:
arr1 = np.zeros((3,3))

In [56]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [60]:
arr2 = np.identity(5)

In [61]:
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])